image: ridistory/ci-base

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_DRIVER: overlay
  REPOSITORY_URL: $REPOSITORY_URL
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_REGION

stages:
  - test
  - build
  - image

gradle-test:
  stage: test
  only:
    - feature/deploy_setting
  script:
    - ./gradlew clean generateDbJooqSchemaSource test --stacktrace

gradle-build:
  stage: build
  only:
    - feature/deploy_setting
  script:
    - ./gradlew build --stacktrace

docker-build:
  image: docker:latest
  services:
    - docker:dind
  stage: image
  only:
    - feature/deploy_setting
  script:
    # install awscli
    - apk update && apk add python3
    - pip3 install awscli

    # aws ecr login
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - "`aws ecr get-login --no-include-email --region=$AWS_REGION`"

    # build image
    - docker build -t $REPOSITORY_URL -f docker/videoshop/Dockerfile --build-arg version=0.0.1 .

    # push image
    - docker push $REPOSITORY_URL
