image: ridistory/ci-base

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_DRIVER: overlay
  REPOSITORY_URL: $REPOSITORY_URL
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_REGION

before_script:
  - export GRADLE_USER_HOME=/cache/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test
  - build
  - image

gradle-test:
  stage: test
  only:
    - feature/deploy_setting
  script:
    - ./gradlew clean generateDbJooqSchemaSource test --stacktrace
  artifacts:
    paths:
      - src/
      - .gradle/

gradle-build:
  stage: build
  only:
    - feature/deploy_setting
  script:
    - ./gradlew build --stacktrace
  artifacts:
    paths:
      - src/
      - .gradle/
      - build/


docker-build:
  image: ridistory/image-builder:latest
  services:
    - docker:dind
  stage: image
  only:
    - feature/deploy_setting
  script:
    # aws ecr login
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - "`aws ecr get-login --no-include-email --region=$AWS_REGION`"

    # build image
    - docker build -t $REPOSITORY_URL -f docker/videoshop/Dockerfile --build-arg version=0.0.1 .

    # push image
    - docker push $REPOSITORY_URL
