image: 805839038026.dkr.ecr.ap-northeast-2.amazonaws.com/base-videoshop:latest

variables:
  repository_url: 805839038026.dkr.ecr.ap-northeast-2.amazonaws.com/videoshop/latest

stages:
  - test
  - build
  - image

before_script:
  - ./gradlew clean generateDbJooqSchemaSource --stacktrace

gradle-test:
  stage: test
  only:
    - feature/deploy_setting
  script:
    - ./gradlew test --stacktrace

gradle-build:
  stage: build
  only:
    - feature/deploy_setting
  script:
    - ./gradlew build --stacktrace

docker-build:
  stage: image
  only:
    - feature/deploy_setting
  script:
    - docker build -t $repository_url videoshop -f docker/videoshop/Dockerfile --build-arg version=0.0.1 .
    - docker tag videoshop:latest $repository_url
    - docker push $repository_url
