image: docker:latest

variables:
  repository_url: 805839038026.dkr.ecr.ap-northeast-2.amazonaws.com

before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli

stages:
  - test
  - build
  - image

gradle-test:
  stage: test
  script:
    - ./gradlew test

gradle-build:
  stage: build
  script:
    - ./gradlew build

docker-build:
  stage: image
  script:
    - $(aws ecr get-login --region ap-northeast-2)
    - docker build -t $repository_url/videoshop:latest videoshop -f docker/videoshop/Dockerfile --build-arg version=0.0.1 .
    - docker tag videoshop:latest $repository_url/videoshop:latest
    - docker push $repository_url/videoshop:latest
