image 805839038026.dkr.ecr.ap-northeast-2.amazonaws.com/base-videoshop:latest

before_script:

stages:
  - test
  - build
  - image
#  - deploy

gradle-test:
  stage: test
  script: "gradle test"

gradle-build:
  stage: build
  script: "gradle build"

docker-build:
  stage: image
  script:
    - docker build -t videoshop -f docker/videoshop/Dockerfile --build-arg version=0.0.1 .
    - docker tag videoshop:latest 805839038026.dkr.ecr.ap-northeast-2.amazonaws.com/videoshop:latest
    - docker push 805839038026.dkr.ecr.ap-northeast-2.amazonaws.com/videoshop:latest
