
spring:
  profiles: prod
  datasource:
    password:
    username:
    driver-class-name: "com.mysql.jdbc.Driver"
    url:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  redis:
    port: 6379
    host: "127.0.0.1"


handlebars:
  exposeRequestAttributes: true
  suffix: .hbs
  cache: false
