server:
  port: 8080

---

spring:
  application:
    name: video-rental-shop
  jooq:
    sql-dialect: mysql
#logging:
#  config: classpath:logback-spring.xml

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: junglekim
---

#zookeeper:
#  enabled: true
#  connectString: 52.78.50.157:2181

handlebars:
  suffix: .html