
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  redis:
    port: 6379
    host: "127.0.0.1"
#    password: "rbx120303"
#    database: 0


handlebars:
  exposeRequestAttributes: true
  suffix: .hbs
  cache: false

datasource:
  videoshop:
    username:
    password:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL"
  history:
    username:
    password:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL"
