server:
  port: 8080

---

spring:
  application:
    name: video-rental-shop
  profiles:
    active: dev
  jooq:
    sql-dialect: mysql
logging:
  config: classpath:logback-spring.xml

---

zookeeper:
  enabled: true
  connectString: localhost:2181
