
spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  redis:
    port: 6379
    host: "127.0.0.1"


handlebars:
  exposeRequestAttributes: true
  suffix: .hbs
  cache: false
  resolver:
    method: true

datasource:
  videoshop:
    username: storydev
    password: ENC(h2WUkeVO4a9WmSThMYWWVIp51O9vhZu/)
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://storydev.cemib2jfp9g1.ap-northeast-2.rds.amazonaws.com:3306/tmp"
  history:
    username: storydev
    password: ENC(h2WUkeVO4a9WmSThMYWWVIp51O9vhZu/)
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://storydev.cemib2jfp9g1.ap-northeast-2.rds.amazonaws.com:3306/tmp_log"
